-- Add TABLE_JOIN_REQUEST notification type and HOSTED_TABLE_MENU refund type
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TABLE_JOIN_REQUEST';
ALTER TYPE "RefundType" ADD VALUE IF NOT EXISTS 'HOSTED_TABLE_MENU';
